const projects = [
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 03 - Introdução à HTML e CSS',
    Nome: 'Projeto Lessons Learned',
    Stack: ['HTML', 'CSS'],
    Descrição: 'Criar um site que com uma série de informações a respeito do que foi aprendido nos três blocos iniciais do curso na Trybe, estilizado de forma apropriada.',
    Imagem: '../images/ProjectLessonsLearned.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 04 - Introdução à JavaScript e Lógica de Programação',
    Nome: 'Projeto - Playground Function',
    Stack: ['JavaScript'],
    Descrição: 'Implementar funções a partir de requisitos.',
    Imagem: '../images/ProjectPlaygroundFunctions.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 05 - JavaScript: DOM, Eventos e Web Storage',
    Nome: 'Projeto 05 - Arte com Pixels',
    Stack: ['JavaScript', 'DOM'],
    Descrição: 'Implementar um editor de arte com pixels. Ou seja, dada uma paleta de cores e um quadro composto por pixels, permitir que quem usa consiga pintar o que quiser no quadro!',
    Imagem: '../images/ProjectPixelsArt.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 05 - JavaScript: DOM, Eventos e Web Storage',
    Nome: 'Projeto 06 - Meme Generator',
    Stack: ['JavaScript', 'DOM'],
    Descrição: 'Criar uma página com Gerador de Meme, fazer upload de uma imagem para a página e adicione algum texto sobre ela.',
    Imagem: '../images/ProjectMemeGenerator.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 05 - JavaScript: DOM, Eventos e Web Storage',
    Nome: 'Projeto 07 - Lista de tarefas',
    Stack: ['JavaScript', 'DOM'],
    Descrição: 'Construir uma página para controle de Lista de Tarefas, integrando conhecimentos de HTML , CSS e JavaScript.',
    Imagem: '../images/ProjectTodoList.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 06 - HTML e CSS: Forms, Flexbox e Responsivo',
    Nome: 'Projeto 08 - Página inicial do Facebook',
    Stack: ['JavaScript', 'CSS', 'HTML'],
    Descrição: 'Recriar o icônico layout da tela de cadastro da rede social mais acessada do mundo, o Facebook, com uma audiência de mais de 2,3 bilhões de usuários por mês.',
    Imagem: '../images/ProjectFacebookSignup.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 07 - Introdução à JavaScript ES6 e Testes Unitários',
    Nome: 'Projeto 09 - JavaScript Testes Unitários',
    Stack: ['NodeJS', 'Unit Test', 'JavaScript'],
    Descrição: 'Implementar funções a partir de requisitos e testes unitários, utilizando o módulo Assert do NodeJS para verificar o correto funcionamento dessas funções.',
    Imagem: '../images/ProjectJsUnitTests.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 08 - Higher Order Functions do JavaScript ES6',
    Nome: 'Projeto 10 - Zoo Functions',
    Stack: ['JavaScript', 'Higher Order Functions'],
    Descrição: 'Simular um sistema de relatório de um zoológico. Você desenvolverá um conjunto de funções capazes de recuperar vários tipos de informações acerca do zoológico e de seu funcionamento. O sistema possui informações a respeito dos animais presentes no zoológico, colaboradores, horários de funcionamento e uma tabela de preços que varia de acordo com a idade das pessoas que o visitam.',
    Imagem: '../images/ProjectZooFunctions.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 09 - JavaScript Assíncrono e Promises',
    Nome: 'Projeto 11 - Carrinho de Compras',
    Stack: ['Async', 'Promises'],
    Descrição: 'Desenvolver um carrinho de compras. Este projeto visa colocar em prática todo o conteúdo aprendido sobre Web Storage e assincronicidade em JavaScript .',
    Imagem: '../images/ProjectShoppingCart.png',
  },
  {
    Módulo: 'Mód. I - Fundamentos do Desenvolvimento Web',
    Bloco: 'Bloco 10 - Testes automatizados com Jest',
    Nome: 'Projeto 12 - Jest Assíncrono e Mocking',
    Stack: ['Jest', 'Tests', 'Mock'],
    Descrição: 'Implementar testes utilizando o Jest para verificar o correto funcionamento de uma série de funções.',
    Imagem: '../images/ProjectJest.png',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 11 - Introdução à React',
    Nome: 'Projeto 13 - Movie Cards Library',
    Stack: ['React'],
    Descrição: 'Desenvolver site usando React, onde este será uma biblioteca de cartões contendo informações sobre filmes.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 12 - Componentes com Estado, Eventos e Formulários com React',
    Nome: 'Projeto 14 - Movie Cards Library Stateful',
    Stack: ['React'],
    Descrição: 'Neste projeto também vai desenvolver uma biblioteca de filmes, tornando-a dinâmica via interação do usuário! Deve-se gerenciar estado e integrá-lo com capturas de eventos e formulários.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 13 - Ciclo de Vida de Componentes e React Router',
    Nome: 'Projeto 15 - Movie Cards Library CRUD',
    Stack: ['React', 'CRUD', 'React Router', 'lifecycle-methods'],
    Descrição: 'Agora a biblioteca terá diversas rotas, cada uma responsável por uma parte da funcionalidade. Desenvolver um app que permite criar, atualizar, visualizar e apagar cartões, colocando em prática os conceitos de React Router e lifecycle-methods',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 14 - Metodologias Ágeis',
    Nome: 'Projeto 16 - Frontend Online Store',
    Stack: ['Kanban', 'React'],
    Descrição: 'Construir o Front-End de um e-commerce, uma loja online, alimentada por uma API do Mercado Livre. Projeto em grupo! O objetivo é sedimentar tudo o que foi aprendido sobre React até aqui, enquanto praticam a organização de um projeto em time com a metodologia ágil e Kanban.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 15 - Testes automatizados com React Testing Library',
    Nome: 'Projeto 17 - Testes em React',
    Stack: ['RTL', 'React', 'Testes'],
    Descrição: 'Escrever testes automatizados para uma aplicação React.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 16 - Gerenciamento de estado com Redux',
    Nome: 'Projeto 18 - Trybe Wallet',
    Stack: ['Redux', 'React'],
    Descrição: 'Criar uma aplicação que computa gastos em diferentes moedas e converte tudo para uma única moeda, que pode ser escolhida por quem usa. Utilizando Redux para gerenciamento de estado do React.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 17 - Projeto Jogo de Trivia',
    Nome: 'Projeto 19 - Jogo de Trivia',
    Stack: ['Kanban', 'React', 'Redux'],
    Descrição: 'Desenvolver um jogo de perguntas e respostas baseado no jogo Trivia, parecido um show do milhão americano, utilizando React e Redux. Projeto em Grupo.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 18 - Context API e React Hooks',
    Nome: 'Projeto 20 - StarWars DataTable com Context API e Hooks',
    Stack: ['Context API', 'Hooks', 'React'],
    Descrição: 'Desenvolver uma tabela por meio de uma Requisição API, com dados de Planetas dos filmes StarWars, utilizando Context API e Hooks para controle de filtros.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. II - Desenvolvimento Front-end',
    Bloco: 'Bloco 19 - Projeto App de Receitas',
    Nome: 'Projeto 21 - App de Receitas',
    Stack: ['Redux', 'Context API', 'Hooks', 'Kanban', 'Figma'],
    Descrição: 'Desenvolver um sistema que permite visualizar, buscar, filtrar, favoritar, compartilhar e acompanhar o processo de preparação de receitas e drinks. A base de dados serão 2 APIs distintas, uma para comidas e outra para bebidas. Utilizando conceitos de Redux, Context API e React Hooks. Projeto em grupo.',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. III - Desenvolvimento Back-end',
    Bloco: '',
    Nome: 'Projeto 22 - ',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: 'Mód. III - Desenvolvimento Back-end',
    Bloco: '',
    Nome: 'Projeto 23 - ',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },
  {
    Módulo: '',
    Bloco: '',
    Nome: '',
    Stack: ['', ''],
    Descrição: '',
    Imagem: '../images/',
  },

];

export default projects;
